alias.c
t_alias* new_alias(t_alias *old, char *first, char *sec)
References s_alias::next, s_alias::old.
Referenced by check_recur.
char* alias_finder(t_alias *s, char *alias)
References my_strcmp, s_alias::new, s_alias::next, s_alias::old.
Referenced by alias_find.
int get_line_file()
References RCNAME, gnl.
Referenced by get_bash.
char* alias_find(t_alias *alias, char *to_find)
References alias_finder, my_strcmp, my_strdup, alias_find, end_find.
Referenced by alias_find, concat_alias.
t_data* check_recur(t_data *data, char *old, char *new)
References s_data::alias, new_alias.
Referenced by get_old_new.