alias_etc.c
int setbashenv(int i, char *str, int start, char **to_set)
References my_strndup.
Referenced by bashset.
int bashset(char *str, t_data *data)
References my_strndup, setbashenv, my_setenv, FAILURE.
Referenced by get_all_alias.
char* end_find(char *new, char *prev, char *to_find)
Referenced by alias_find.
char* concat_alias(char *str, t_alias *list_alias)
References alias_find, my_strndup, my_strdup, my_strconcat.
Referenced by add_cmd.