builtin.h
ESCAPE
FAILURE
Referenced by bashset, my_unsetenv, my_setenv, my_env, my_echo, my_cd_error, set_pwd_old_pwd, my_cd, my_replace_key, my_redir_builtin, builtin, exe_cmd.
NO_MATCH
Referenced by builtin.
SUCCESS
Referenced by my_unsetenv, my_setenv, my_env, my_echo, set_pwd_old_pwd, my_cd, my_replace_key, exe_cmd.
EXIT
Referenced by my_exit, exe_cmd.
typedef struct s_bref t_bref
int my_redir_builtin(t_data *data, t_cmd *cmd)
References FAILURE, redirection_right, s_cmd::redi_r, redirection_left, s_cmd::redi_l, builtin, s_cmd::tab.
Referenced by exe_cmd.
char** cattab_ext(char *new)
Referenced by my_cattab.
int my_cd_error(char *str)
References FAILURE.
Referenced by my_setenv, my_cd.
int my_replace_key(char **expr, t_data *data)
References s_data::env, FAILURE, get_env_value, delete_first_word, SUCCESS.
Referenced by builtin.
char* my_cstrconcat(char *s1, char *s2)
References my_strlen.
Referenced by my_setenv, get_new_pwd, set_pwd_old_pwd, my_cd.
char* get_env_value(char **env, char *key, int *offset)
Referenced by my_unsetenv, my_setenv, set_pwd_old_pwd, my_cd, my_replace_key, pars_ps1, exe_path, pars_tilde, case_name, case_host, case_pwd, case_last_dir, case_term.
int my_print(char *str, char inter, char noret, char *nextword)
References my_interpret, my_putchar.
Referenced by my_echo.
char** my_epurtab(char **tab)
Referenced by my_unsetenv.
char** my_cattab(char **tab, char *new)
References cattab_ext.
Referenced by my_setenv.
int my_getnbr_base(char *str, char *base, int *offset, int i)
Referenced by other_echo_case.
int my_cd(char **, t_data *)
References get_env_value, s_data::env, my_cd_error, my_cstrconcat, FAILURE, set_pwd_old_pwd, SUCCESS.
Referenced by builtin.
int my_exit(char **, t_data *)
References s_data::return_exit, my_getnbr, EXIT.
Referenced by builtin.
int my_env(char **, t_data *)
References s_data::env, my_strcmp, FAILURE, SUCCESS.
Referenced by builtin.
int my_setenv(char **, t_data *)
References my_cd_error, FAILURE, my_cstrconcat, get_env_value, s_data::env, my_cattab, SUCCESS.
Referenced by bashset, builtin.
int my_unsetenv(char **, t_data *)
References s_data::env, SUCCESS, get_env_value, FAILURE, my_epurtab.
Referenced by builtin.
int my_echo(char **, t_data *)
References FAILURE, my_strcmp, my_print, SUCCESS.
Referenced by builtin.