utils.c
int my_getnbr_base(char *str, char *base, int *offset, int i)
Referenced by other_echo_case.
char* get_env_value(char **env, char *key, int *offset)
Referenced by my_unsetenv, my_setenv, set_pwd_old_pwd, my_cd, my_replace_key, pars_ps1, exe_path, pars_tilde, case_name, case_host, case_pwd, case_last_dir, case_term.
char** cattab_ext(char *new)
Referenced by my_cattab.