builtin.c
int my_unsetenv(char **expr, t_data *data)
References s_data::env, SUCCESS, get_env_value, FAILURE, my_epurtab.
Referenced by builtin.
int my_setenv(char **expr, t_data *data)
References my_cd_error, FAILURE, my_cstrconcat, get_env_value, s_data::env, my_cattab, SUCCESS.
Referenced by bashset, builtin.
int my_env(char **expr, t_data *data)
References s_data::env, my_strcmp, FAILURE, SUCCESS.
Referenced by builtin.
int my_exit(char **expr, t_data *data)
References s_data::return_exit, my_getnbr, EXIT.
Referenced by builtin.
int my_echo(char **expr, t_data *data)
References FAILURE, my_strcmp, my_print, SUCCESS.
Referenced by builtin.