cd.c
int my_cd_error(char *str)
References FAILURE.
Referenced by my_setenv, my_cd.
char* get_new_pwd(char *pwd, char *path)
References my_cstrconcat, my_strcmp, my_strlen.
Referenced by set_pwd_old_pwd.
int set_pwd_old_pwd(char **env, char *path)
References get_env_value, my_strlen, my_strcpy, my_cstrconcat, FAILURE, get_new_pwd, my_strdup, SUCCESS.
Referenced by my_cd.
int my_cd(char **expr, t_data *data)
References get_env_value, s_data::env, my_cd_error, my_cstrconcat, FAILURE, set_pwd_old_pwd, SUCCESS.
Referenced by builtin.