clear_line.c
void clean_line()
References my_putchar.
Referenced by delete_char, delete_backward, up, down.