errors.c
int error_cmd_not_found(char *cmd, int exit)
Referenced by exe_cmd, check_cmd.
int error_syntax_error(int exit)
Referenced by is_sep_cmd, add_redi.