exe_cmd.c
int exe_function(t_data *data, t_cmd *cmd, char *cmd1, int pipe)
References is_exe, redirection_right, s_cmd::redi_r, redirection_left, s_cmd::redi_l, s_cmd::tab, s_data::env, s_data::return_exe, segfault.
Referenced by loop_exe_path, exe_cmd.
char* make_path(char *path, char *str)
References malloc_str, my_strlen, my_strcat.
Referenced by loop_exe_path.
int loop_exe_path(t_data *data, t_cmd *cmd, char *paths, int pipe)
References make_path, s_cmd::tab, exe_function.
Referenced by exe_path.
int exe_path(t_data *data, t_cmd *cmd, int pipe)
References s_cmd::tab, get_env_value, s_data::env, default_path, str_to_word_tab, loop_exe_path.
Referenced by exe_cmd.
int exe_cmd(t_data *data, t_cmd *cmd, int pipe)
References s_cmd::tab, my_strlen, parsing_globing, pars_tilde, my_redir_builtin, EXIT, SUCCESS, FAILURE, exe_path, exe_function, error_cmd_not_found.
Referenced by last_pipe, loop_pipe, first_pipe.