forbuiltin.c
char g_ref[8][2][8][2]
Referenced by my_interpret.
void other_echo_case(char *str, int *i, char done)
References my_putchar, my_getnbr_base.
Referenced by my_interpret.
int my_interpret(char *str, int i, int k, char done)
References g_ref, my_putchar, other_echo_case.
Referenced by my_print.
int my_print(char *str, char inter, char noret, char *nextword)
References my_interpret, my_putchar.
Referenced by my_echo.
char** my_epurtab(char **tab)
Referenced by my_unsetenv.
char** my_cattab(char **tab, char *new)
References cattab_ext.
Referenced by my_setenv.