functions_complete.c
int is_slash(char *str)
Referenced by epur_slash, my_write_tab.
char* epur_slash(char *str)
References my_strlen, is_slash, my_strcpy_from.
Referenced by auto_complete.
void my_write_tab(char **tab)
References my_putchar, is_slash, my_strlen.
Referenced by auto_complete.