gere_key.c
void* gere_history(char *cmd, char *c, t_history *list, t_stock *ptr)
References clean, up, down, s_stock::cmd, s_stock::c, s_stock::pos, my_strlen.
Referenced by loop.
void* gere_char(t_stock *ptr)
References s_stock::c, s_stock::pos, clean_screen, s_stock::cmd, my_strlen, delete_backward, delete_char, gere_tab, add_char.
Referenced by loop.
void* gere_arrow(t_stock *ptr)
References s_stock::c, my_strlen, s_stock::cmd, s_stock::pos, print_cursor_left, print_cursor_right.
Referenced by loop.
static void* complete_cmd(t_stock *ptr, char *complete, char *tmp)
void gere_tab(t_stock *ptr)
References last_word, s_stock::cmd, s_stock::pos, auto_complete, my_putchar, pars_ps1, g_data, s_data::env, my_putstr, print_cursor_left, my_strlen.
Referenced by gere_char.