get_next_line.c
char* my_read(int fd, char *str)
References BUFF_SIZE, my_strlen, my_strncat.
Referenced by get_next_line.
char* new_str(char *str, int *i, int j)
Referenced by get_next_line, my_strdup, my_strndup, calc_new_str.
char* get_next_line(int fd)
References my_read, new_str, my_strlen, get_next_line.
Referenced by get_next_line.