getvar.c
void delete_first_word(char **wtab)
Referenced by my_replace_key.
int my_replace_key(char **expr, t_data *data)
References s_data::env, FAILURE, get_env_value, delete_first_word, SUCCESS.
Referenced by builtin.
char* my_cstrconcat(char *s1, char *s2)
References my_strlen.
Referenced by my_setenv, get_new_pwd, set_pwd_old_pwd, my_cd.