lib.h
char* malloc_str(int)
char* my_strcat(char *, char *)
Referenced by make_path, pars_tilde, add_char, delete_char, delete_backward.
char* my_strncat(char *, char *, int)
References my_strlen.
Referenced by my_read, str_to_word_tab.
char* get_next_line(int)
References my_read, new_str, my_strlen, get_next_line.
Referenced by get_next_line.
char* my_strcpy(char *, char *)
Referenced by set_pwd_old_pwd, my_strdup, add_char, delete_char, delete_backward, up, down.
char* my_strncpy(char *, char *, int)
Referenced by my_strndup, add_char, delete_char, delete_backward.
char* my_strcpy_from(char *, char *, int)
Referenced by epur_slash, add_char, delete_char, delete_backward.
void my_putchar(char, int fd)
Referenced by my_write_tab, other_echo_case, my_interpret, my_print, case_beep, launch_format, write_list_redi, my_put_nbr, clean_screen, clean_line, gere_tab, add_char, delete_char, delete_backward, up, down, get_cmd.
void my_putstr(char *, int)
Referenced by pars_ps1, write_list_redi, double_redi_left, clean_screen, gere_tab, add_char, delete_char, delete_backward, up, down, print_cursor_left, print_cursor_right, get_cmd, case_name, case_host, case_pwd, case_last_dir, case_term.
void my_put_nbr(int)
References my_putchar, power_10.
void my_strcat_from(char *, char *, int)
References my_strlen.
int my_getnbr(char *)
References my_getnbr_2.
Referenced by my_exit.
int* my_strcmp(char *, char *)
Referenced by alias_finder, alias_find, my_env, my_echo, get_new_pwd, is_builtin, double_redi_left.
int my_strlen(char *)
Referenced by my_strconcat, epur_slash, my_write_tab, get_new_pwd, set_pwd_old_pwd, my_cstrconcat, make_path, exe_cmd, my_read, get_next_line, my_strcat_from, my_strdup, my_strncat, my_strndup, pars_tilde, gere_history, gere_char, gere_arrow, gere_tab, last_word, change_word, loop, add_char, delete_char, delete_backward, up, down, get_cmd.
int len_tab(char **)
Referenced by add_word_to_tab.
char* my_strndup(char *src, int nb)
References new_str, my_strlen, my_strncpy.
Referenced by setbashenv, bashset, concat_alias, get_old, get_old_new.
char* my_strdup(char *src)
References new_str, my_strlen, my_strcpy.
Referenced by alias_find, concat_alias, get_bash, set_pwd_old_pwd, case_pwd.
int my_strncmp(char *a, char *b, int n)
Referenced by get_all_alias, case_pwd.