loop_read.c
void clean(char *c, const int nb)
Referenced by gere_history, init_stock, loop, up, down.
static void* go_start_line(t_stock *ptr)
static void* go_end_line(t_stock *ptr)
void* change_word(t_stock *ptr)
References s_stock::pos, s_stock::c, s_stock::cmd, print_cursor_left, my_strlen, print_cursor_right.
Referenced by loop.
char* loop(t_history *list)
References init_stock, s_stock::c, clean, gere_history, s_stock::cmd, gere_arrow, my_strlen, change_word, gere_char.