modif_cmd.c
void* add_char(t_stock *ptr)
References my_strlen, s_stock::cmd, s_stock::pos, my_putchar, s_stock::c, my_strncpy, my_strcat, my_strcpy_from, my_strcpy, pars_ps1, g_data, s_data::env, my_putstr, print_cursor_left.
Referenced by gere_char.
void* delete_char(t_stock *ptr)
References my_strlen, s_stock::cmd, s_stock::pos, clean_line, my_putchar, pars_ps1, g_data, s_data::env, my_putstr, my_strncpy, my_strcpy_from, my_strcpy, my_strcat, print_cursor_left.
Referenced by gere_char.
void* delete_backward(t_stock *ptr)
References my_strlen, s_stock::cmd, s_stock::pos, my_strncpy, my_strcpy_from, my_strcpy, my_strcat, clean_line, my_putchar, pars_ps1, g_data, s_data::env, my_putstr, print_cursor_left.
Referenced by gere_char.