my_strlen.c
int my_strlen(char *str)
Referenced by my_strconcat, epur_slash, my_write_tab, get_new_pwd, set_pwd_old_pwd, my_cstrconcat, make_path, exe_cmd, my_read, get_next_line, my_strcat_from, my_strdup, my_strncat, my_strndup, pars_tilde, gere_history, gere_char, gere_arrow, gere_tab, last_word, change_word, loop, add_char, delete_char, delete_backward, up, down, get_cmd.