my_putstr.c
void my_putstr(char *str, int fd)
Referenced by pars_ps1, write_list_redi, double_redi_left, clean_screen, gere_tab, add_char, delete_char, delete_backward, up, down, print_cursor_left, print_cursor_right, get_cmd, case_name, case_host, case_pwd, case_last_dir, case_term.