my_putchar.c
void my_putchar(char c, int fd)
Referenced by my_write_tab, other_echo_case, my_interpret, my_print, case_beep, launch_format, write_list_redi, my_put_nbr, clean_screen, clean_line, gere_tab, add_char, delete_char, delete_backward, up, down, get_cmd.