my_strcmp.c
int my_strcmp(char *s1, char *s2)
Referenced by alias_finder, alias_find, my_env, my_echo, get_new_pwd, is_builtin, double_redi_left.