my_getnbr.c
int check(int nbr, int nbr_z)
Referenced by my_getnbr_2.
int my_getnbr_2(char *str, int signe)
References check.
Referenced by my_getnbr.
int my_getnbr(char *str)
References my_getnbr_2.
Referenced by my_exit.