my_strncpy.c
char * my_strncpy(char *dest, char *src, int nb)
Referenced by my_strndup, add_char, delete_char, delete_backward.