my_strcpy.c
char * my_strcpy(char *dest, char *src)
Referenced by set_pwd_old_pwd, my_strdup, add_char, delete_char, delete_backward, up, down.