my_strcat.c
char* my_strcat(char *dest, char *src)
Referenced by make_path, pars_tilde, add_char, delete_char, delete_backward.