my_strndup.c
char* my_strndup(char *src, int nb)
References new_str, my_strlen, my_strncpy.
Referenced by setbashenv, bashset, concat_alias, get_old, get_old_new.