my_strcpy_from.c
char* my_strcpy_from(char *dest, char *src, int nb)
Referenced by epur_slash, add_char, delete_char, delete_backward.