parsing_general.c
int is_sep_cmd(char *str, int i)
References error_syntax_error.
Referenced by parsing_general.
t_cmds* new_cmds(char *new_str, char sep)
References parsing_pipe, s_cmds::sep.
Referenced by add_cmds.
t_cmds* add_cmds(char *new_str, t_cmds **cmds, t_cmds **tmp, char sep)
References new_cmds, s_cmds::next.
Referenced by parsing_general.
void go_next_cmds(char *str, int *i, int *i_save)
Referenced by parsing_general.
t_cmds* parsing_general(char *str)
References is_sep_cmd, add_cmds, calc_new_str, go_next_cmds.