parsing_pipe.c
void next_cmd(char *str, int *i, int *i_save)
Referenced by parsing_pipe.
char* calc_new_str(char *str, int i, int i_save)
References new_str.
Referenced by parsing_general, parsing_pipe.
t_cmd* add_cmd(char *new_str, t_cmd **cmd, t_cmd **tmp)
References concat_alias, g_data, s_data::alias, parsing_cmd.
Referenced by parsing_pipe.
t_cmd* parsing_pipe(char *str)
References add_cmd, calc_new_str, next_cmd.
Referenced by new_cmds.