parsing_cmd.c
int is_redi(char c)
Referenced by index_end_word, parsing_cmd, add_redi.
int index_end_word(char *str_cmd, int *i)
References is_redi.
Referenced by add_word_to_tab, add_redi.
int add_word_to_tab(char *str_cmd, t_cmd *cmd, int *i)
References index_end_word, s_cmd::tab, len_tab.
Referenced by parsing_cmd.
t_cmd* init_parsing()
References s_cmd::redi_r, s_cmd::redi_l, s_cmd::next, s_cmd::tab.
Referenced by parsing_cmd.
t_cmd* parsing_cmd(char *str_cmd)
References init_parsing, is_redi, add_redi, add_word_to_tab.
Referenced by add_cmd.