pars_alias.c
char** get_bash()
References get_line_file, RCNAME, gnl, my_strdup.
Referenced by pars_alias.
char* get_old(char *str, int x, int i)
References my_strndup.
Referenced by get_old_new.
t_data* get_old_new(char *str, t_data *data, int x)
References my_strndup, get_old, check_recur.
Referenced by get_all_alias.
t_data* get_all_alias(t_data *data, char **bash, int x)
References my_strncmp, get_old_new, bashset.
Referenced by pars_alias.
int pars_alias(t_data *data)
References get_bash, get_all_alias.