pipe.c
int check_cmd(t_data *data, t_cmds *cmds)
References s_cmds::cmd, s_cmd::tab, get_bin_path, is_builtin, error_cmd_not_found.
Referenced by last_pipe, loop_pipe, first_pipe.
int last_pipe(t_data *data, int pipefd[2], t_cmds *cmds)
References check_cmd, exe_cmd, s_cmds::cmd.
Referenced by exe_pipe.
int loop_pipe(t_data *data, int pipefd[2], t_cmds *cmds)
References s_cmds::cmd, s_cmd::next, check_cmd, exe_cmd.
Referenced by exe_pipe.
int first_pipe(t_data *data, int pipefd[2], t_cmds *cmds)
References check_cmd, exe_cmd, s_cmds::cmd, s_cmd::next.
Referenced by exe_pipe.
int exe_pipe(t_data *data, t_cmds *cmds)
References first_pipe, loop_pipe, last_pipe, s_data::return_exe, segfault.