prompt.c
char* clear_str(char *str, int l)
char* epure_str(char *str)
Referenced by sh.
char* read_cmd()
References malloc_str, my_strlen, my_strncat.
Referenced by double_redi_left, sh.