utils.c
t_format g_tab_ptr[][]
void case_beep(char **env)
References my_putchar.
int launch_format(int *i, char *str, char **env)
References FORMAT_CHAR, NAME_CHAR, HOST_CHAR, PWD_CHAR, LAST_DIR_CHAR, TERM_CHAR, BEEP_CHAR, s_format::ptr_tab, my_putchar.
Referenced by get_ps1.
int get_ps1(char *str, char **env)
References launch_format.
Referenced by pars_ps1.
char* fix_ps1(char *ps1)
Referenced by pars_ps1.
int pars_ps1(char **env)
References my_putstr, get_env_value, get_ps1, fix_ps1.
Referenced by clean_screen, gere_tab, add_char, delete_char, delete_backward, up, down.