redirection_left.c
int open_file_rd(char *name)
Referenced by redirection_left.
t_list_line* add_end_list(t_list_line *list, char *str)
References s_list_line::line, s_list_line::next.
Referenced by double_redi_left.
int write_list_redi(t_list_line *list)
References my_putstr, s_list_line::line, my_putchar, s_list_line::next.
Referenced by double_redi_left.
int double_redi_left(char *stop)
References my_putstr, read_cmd, my_strcmp, add_end_list, write_list_redi.
Referenced by redirection_left.
int redirection_left(t_list *list_r)
References s_list::double_redi, double_redi_left, s_list::file, open_file_rd, s_list::next.
Referenced by my_redir_builtin, exe_function.