redirection.c
void set_last_in_list(t_list *redi_r_l, t_list *new)
References s_list::next.
Referenced by set_redi.
int set_redi(t_list *redi, t_cmd *cmd, char c, char c2)
References s_cmd::redi_r, set_last_in_list, s_list::double_redi, s_cmd::redi_l.
Referenced by add_redi.
int add_redi(char *str_cmd, t_cmd *cmd, int *i)
References set_redi, s_list::next, is_redi, error_syntax_error, index_end_word, s_list::file.
Referenced by parsing_cmd.