redirection_right.c
int open_file_wr(char *name, int double_redi)
Referenced by redirection_right.
int redirection_right(t_list *list_r)
References open_file_wr, s_list::file, s_list::double_redi, s_list::next.
Referenced by my_redir_builtin, exe_function.