sh.c
int count_pipe(t_cmd *cmd)
References s_cmd::next.
Referenced by call_exe.
int check_exe(int return_exe, char sep)
Referenced by sh.
int call_exe(t_data *data)
References count_pipe, s_data::cmds, s_cmds::cmd, exe_pipe, exe_cmd.
Referenced by sh.
int sh(t_data *data)
References s_data::list, pars_ps1, s_data::env, s_data::dynam_prompt, read_cmd, get_cmd, s_data::cmds, parsing_general, epure_str, check_exe, s_data::return_exe, call_exe, s_cmds::sep, s_cmds::next.
Referenced by main.