shell.h
READ_SIZE
Referenced by gnl.
RCNAME
Referenced by get_line_file, get_bash.
typedef struct s_alias t_alias
typedef struct s_list_line t_list_line
typedef struct s_list t_list
typedef struct s_cmd t_cmd
typedef struct s_cmds t_cmds
typedef struct s_stock t_stock
typedef struct s_history t_history
typedef struct s_data t_data
t_data* g_data
Referenced by add_cmd, clean_screen, gere_tab, add_char, delete_char, delete_backward, up, down.
t_cmd* parsing_cmd(char *)
References init_parsing, is_redi, add_redi, add_word_to_tab.
Referenced by add_cmd.
t_cmd* parsing_pipe(char *)
References add_cmd, calc_new_str, next_cmd.
Referenced by new_cmds.
t_cmds* parsing_general(char *)
References is_sep_cmd, add_cmds, calc_new_str, go_next_cmds.
t_data* check_recur(t_data *data, char *old, char *new)
References s_data::alias, new_alias.
Referenced by get_old_new.
t_data* get_all_alias(t_data *data, char **bash, int x)
References my_strncmp, get_old_new, bashset.
Referenced by pars_alias.
t_alias* new_alias(t_alias *old, char *first, char *sec)
References s_alias::next, s_alias::old.
Referenced by check_recur.
t_history* insert_list_double(t_history *, char *)
References s_history::data, s_history::prev, s_history::next.
Referenced by get_cmd.
int pars_ps1(char **)
References my_putstr, get_env_value, get_ps1, fix_ps1.
Referenced by clean_screen, gere_tab, add_char, delete_char, delete_backward, up, down.
int bashset(char *str, t_data *data)
References my_strndup, setbashenv, my_setenv, FAILURE.
Referenced by get_all_alias.
int segfault(int)
Referenced by exe_function, exe_pipe.
int is_exe(char *path)
Referenced by exe_function.
int add_redi(char *, t_cmd *, int *)
References set_redi, s_list::next, is_redi, error_syntax_error, index_end_word, s_list::file.
Referenced by parsing_cmd.
int error_syntax_error(int exit)
Referenced by is_sep_cmd, add_redi.
int exe_cmd(t_data *, t_cmd *, int)
References s_cmd::tab, my_strlen, parsing_globing, pars_tilde, my_redir_builtin, EXIT, SUCCESS, FAILURE, exe_path, exe_function, error_cmd_not_found.
Referenced by last_pipe, loop_pipe, first_pipe.
int exe_pipe(t_data *, t_cmds *)
References first_pipe, loop_pipe, last_pipe, s_data::return_exe, segfault.
int sh(t_data *)
int redirection_right(t_list *)
References open_file_wr, s_list::file, s_list::double_redi, s_list::next.
Referenced by my_redir_builtin, exe_function.
int redirection_left(t_list *)
References s_list::double_redi, double_redi_left, s_list::file, open_file_rd, s_list::next.
Referenced by my_redir_builtin, exe_function.
int is_redi(char)
Referenced by index_end_word, parsing_cmd, add_redi.
int builtin(t_data *data, char **cmd)
References my_cd, my_exit, my_env, my_setenv, my_unsetenv, my_echo, my_replace_key, s_bref::builtin, s_data::return_exe, FAILURE, NO_MATCH.
Referenced by my_redir_builtin.
int index_end_word(char *, int *)
References is_redi.
Referenced by add_word_to_tab, add_redi.
int is_stars(char *)
Referenced by parsing_globing.
int clean_screen(char *)
References g_data, s_data::env, my_putchar, pars_ps1, my_putstr.
Referenced by gere_char.
int error_cmd_not_found(char *cmd, int exit)
Referenced by exe_cmd, check_cmd.
int if_stars(char **, char **, int, int)
References return_globing.
Referenced by parsing_globing.
int pars_alias(t_data *data)
References get_bash, get_all_alias.
int get_line_file()
References RCNAME, gnl.
Referenced by get_bash.
int is_slash(char *)
Referenced by epur_slash, my_write_tab.
int is_builtin(char *)
References my_strcmp.
Referenced by check_cmd.
char* epur_slash(char *)
References my_strlen, is_slash, my_strcpy_from.
Referenced by auto_complete.
char* auto_complete(char *)
References my_write_tab, epur_slash.
Referenced by gere_tab.
char* malloc_str(int)
Referenced by make_path, str_to_word_tab.
char* loop(t_history *)
References init_stock, s_stock::c, clean, gere_history, s_stock::cmd, gere_arrow, my_strlen, change_word, gere_char.
char* get_cmd(t_history **)
References my_strlen, insert_list_double, my_putstr, my_putchar.
char* gnl(const int fd)
References READ_SIZE.
Referenced by get_line_file, get_bash.
char* concat_alias(char *, t_alias *)
References alias_find, my_strndup, my_strdup, my_strconcat.
Referenced by add_cmd.
char* make_path(char *path, char *str)
References malloc_str, my_strlen, my_strcat.
Referenced by loop_exe_path.
char* get_bin_path(t_data *data, char *bin)
Referenced by check_cmd.
char* last_word(char *, int)
References my_strlen.
Referenced by gere_tab.
char* my_strconcat(char *s1, char *s2)
References my_strlen.
Referenced by concat_alias, case_pwd.
char* alias_finder(t_alias *s, char *alias)
References my_strcmp, s_alias::new, s_alias::next, s_alias::old.
Referenced by alias_find.
char* alias_find(t_alias *alias, char *to_find)
References alias_finder, my_strcmp, my_strdup, alias_find, end_find.
Referenced by alias_find, concat_alias.
char* end_find(char *new, char *prev, char *to_find)
Referenced by alias_find.
char* up(char *, t_history **, int *, char **)
References clean, clean_line, my_putchar, pars_ps1, g_data, s_data::env, my_putstr, my_strcpy, my_strlen.
Referenced by gere_history.
char* down(char *, t_history **, int *, char **)
References clean, clean_line, my_putchar, pars_ps1, g_data, s_data::env, s_history::prev, my_putstr, my_strcpy, my_strlen.
Referenced by gere_history.
char* calc_new_str(char *, int, int)
References new_str.
Referenced by parsing_general, parsing_pipe.
char* read_cmd()
Referenced by double_redi_left.
char* epure_str(char *)
char** str_to_word_tab(char *, char *)
References how_many_words, is_sep, malloc_str, my_strncat.
Referenced by exe_path.
char** parsing_globing(char **)
References is_stars, if_stars.
Referenced by exe_cmd.
char** return_globing(char *)
Referenced by if_stars.
char** make_env(char **)
char** default_path()
Referenced by exe_path.
char** pars_tilde(t_data *, char **)
References get_env_value, s_data::env, my_strlen, my_strcat.
Referenced by exe_cmd.
void clean_line_prev(t_history *, char *, char *)
void clean_line_next(t_history *, char *, char *)
void clean(char *, int)
Referenced by gere_history, init_stock, loop, up, down.
void clean_line(void)
References my_putchar.
Referenced by delete_char, delete_backward, up, down.
void print_cursor_left(int)
References my_putstr.
Referenced by gere_arrow, gere_tab, change_word, add_char, delete_char, delete_backward.
void print_cursor_right(int)
References my_putstr.
Referenced by gere_arrow, change_word.
void my_write_tab(char **)
References my_putchar, is_slash, my_strlen.
Referenced by auto_complete.
void gere_tab(t_stock *)
References last_word, s_stock::cmd, s_stock::pos, auto_complete, my_putchar, pars_ps1, g_data, s_data::env, my_putstr, print_cursor_left, my_strlen.
Referenced by gere_char.
void* gere_history(char *, char *, t_history *, t_stock *)
References clean, up, down, s_stock::cmd, s_stock::c, s_stock::pos, my_strlen.
Referenced by loop.
void* init_stock(void)
References s_stock::cmd, s_stock::c, s_stock::pos, clean.
Referenced by loop.
void* gere_char(t_stock *)
References s_stock::c, s_stock::pos, clean_screen, s_stock::cmd, my_strlen, delete_backward, delete_char, gere_tab, add_char.
Referenced by loop.
void* gere_arrow(t_stock *)
References s_stock::c, my_strlen, s_stock::cmd, s_stock::pos, print_cursor_left, print_cursor_right.
Referenced by loop.
void* add_char(t_stock *)
References my_strlen, s_stock::cmd, s_stock::pos, my_putchar, s_stock::c, my_strncpy, my_strcat, my_strcpy_from, my_strcpy, pars_ps1, g_data, s_data::env, my_putstr, print_cursor_left.
Referenced by gere_char.
void* delete_char(t_stock *)
References my_strlen, s_stock::cmd, s_stock::pos, clean_line, my_putchar, pars_ps1, g_data, s_data::env, my_putstr, my_strncpy, my_strcpy_from, my_strcpy, my_strcat, print_cursor_left.
Referenced by gere_char.
void* delete_backward(t_stock *)
References my_strlen, s_stock::cmd, s_stock::pos, my_strncpy, my_strcpy_from, my_strcpy, my_strcat, clean_line, my_putchar, pars_ps1, g_data, s_data::env, my_putstr, print_cursor_left.
Referenced by gere_char.