str_to_word_tab.c
int is_sep(char *seps, char c)
Referenced by how_many_words, str_to_word_tab.
int how_many_words(char *str, char *seps)
References is_sep.
Referenced by str_to_word_tab.
char** str_to_word_tab(char *str, char *seps)
References how_many_words, is_sep, malloc_str, my_strncat.
Referenced by exe_path.