.TH "lib/my Directory Reference" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBget_next_line\&.c\fP"
.br
.ti -1c
.RI "file \fBlen_tab\&.c\fP"
.br
.ti -1c
.RI "file \fBmalloc_str\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_getnbr\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_put_nbr\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_putchar\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_putstr\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strcat\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strcat_from\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strcmp\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strcpy\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strcpy_from\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strdup\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strlen\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strncat\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strncmp\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strncpy\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strndup\&.c\fP"
.br
.ti -1c
.RI "file \fBstr_to_word_tab\&.c\fP"
.br
.in -1c
