.TH "parsing Directory Reference" 3 "Sat May 23 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parsing Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBparsing_cmd\&.c\fP"
.br
.ti -1c
.RI "file \fBparsing_general\&.c\fP"
.br
.ti -1c
.RI "file \fBparsing_pipe\&.c\fP"
.br
.ti -1c
.RI "file \fBredirection\&.c\fP"
.br
.in -1c
