.TH "prompt_read_termcaps Directory Reference" 3 "Sat May 23 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prompt_read_termcaps Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclean_screen\&.c\fP"
.br
.ti -1c
.RI "file \fBclear_line\&.c\fP"
.br
.ti -1c
.RI "file \fBgere_key\&.c\fP"
.br
.ti -1c
.RI "file \fBinit\&.c\fP"
.br
.ti -1c
.RI "file \fBinsert_list_double\&.c\fP"
.br
.ti -1c
.RI "file \fBloop_read\&.c\fP"
.br
.ti -1c
.RI "file \fBmodif_cmd\&.c\fP"
.br
.ti -1c
.RI "file \fBmove\&.c\fP"
.br
.ti -1c
.RI "file \fBprint_cursor\&.c\fP"
.br
.ti -1c
.RI "file \fBprompt_dyn\&.c\fP"
.br
.in -1c
