.TH "auto_complete Directory Reference" 3 "Sat May 23 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
auto_complete Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBauto_complete\&.c\fP"
.br
.ti -1c
.RI "file \fBfunctions_complete\&.c\fP"
.br
.in -1c
