.TH "alias Directory Reference" 3 "Sat May 23 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
alias Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBalias\&.c\fP"
.br
.ti -1c
.RI "file \fBalias_etc\&.c\fP"
.br
.ti -1c
.RI "file \fBgnl\&.c\fP"
.br
.ti -1c
.RI "file \fBpars_alias\&.c\fP"
.br
.ti -1c
.RI "file \fBstr_cat\&.c\fP"
.br
.in -1c
