.TH "exe Directory Reference" 3 "Sat May 23 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exe Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBexe_cmd\&.c\fP"
.br
.ti -1c
.RI "file \fBis_builtin\&.c\fP"
.br
.ti -1c
.RI "file \fBpipe\&.c\fP"
.br
.ti -1c
.RI "file \fBredirection_left\&.c\fP"
.br
.ti -1c
.RI "file \fBredirection_right\&.c\fP"
.br
.in -1c
