.TH "auto_complete/auto_complete.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
auto_complete/auto_complete.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <glob\&.h>\fP
.br
\fC#include 'lib\&.h'\fP
.br
\fC#include 'shell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBauto_complete\fP (char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* auto_complete (char *str)"

.PP
Definition at line 57 of file auto_complete\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
