.TH "errors.c" 3 "Fri May 22 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
errors.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBerror_cmd_not_found\fP (char *cmd, int exit)"
.br
.ti -1c
.RI "int \fBerror_syntax_error\fP (int exit)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int error_cmd_not_found (char *cmd, intexit)"

.PP
Definition at line 13 of file errors\&.c\&.
.SS "int error_syntax_error (intexit)"

.PP
Definition at line 19 of file errors\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
