.TH "exe/exe_cmd.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exe/exe_cmd.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/wait\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'shell\&.h'\fP
.br
\fC#include 'builtin\&.h'\fP
.br
\fC#include 'lib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBexe_function\fP (\fBt_data\fP *data, \fBt_cmd\fP *cmd, char *cmd1, int pipe)"
.br
.ti -1c
.RI "char * \fBmake_path\fP (char *path, char *str)"
.br
.ti -1c
.RI "int \fBloop_exe_path\fP (\fBt_data\fP *data, \fBt_cmd\fP *cmd, char *paths, int pipe)"
.br
.ti -1c
.RI "int \fBexe_path\fP (\fBt_data\fP *data, \fBt_cmd\fP *cmd, int pipe)"
.br
.ti -1c
.RI "int \fBexe_cmd\fP (\fBt_data\fP *data, \fBt_cmd\fP *cmd, int pipe)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int exe_cmd (\fBt_data\fP *data, \fBt_cmd\fP *cmd, intpipe)"

.PP
Definition at line 103 of file exe_cmd\&.c\&.
.SS "int exe_function (\fBt_data\fP *data, \fBt_cmd\fP *cmd, char *cmd1, intpipe)"

.PP
Definition at line 19 of file exe_cmd\&.c\&.
.SS "int exe_path (\fBt_data\fP *data, \fBt_cmd\fP *cmd, intpipe)"

.PP
Definition at line 74 of file exe_cmd\&.c\&.
.SS "int loop_exe_path (\fBt_data\fP *data, \fBt_cmd\fP *cmd, char *paths, intpipe)"

.PP
Definition at line 59 of file exe_cmd\&.c\&.
.SS "char* make_path (char *path, char *str)"

.PP
Definition at line 47 of file exe_cmd\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
