.TH "auto_complete/functions_complete.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
auto_complete/functions_complete.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'lib\&.h'\fP
.br
\fC#include 'shell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBis_slash\fP (char *str)"
.br
.ti -1c
.RI "char * \fBepur_slash\fP (char *str)"
.br
.ti -1c
.RI "void \fBmy_write_tab\fP (char **tab)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* epur_slash (char *str)"

.PP
Definition at line 29 of file functions_complete\&.c\&.
.SS "int is_slash (char *str)"

.PP
Definition at line 15 of file functions_complete\&.c\&.
.SS "void my_write_tab (char **tab)"

.PP
Definition at line 48 of file functions_complete\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
