.TH "lib/my/get_next_line.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/get_next_line.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'get_next_line\&.h'\fP
.br
\fC#include 'lib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBmy_read\fP (int fd, char *str)"
.br
.ti -1c
.RI "char * \fBnew_str\fP (char *str, int *i, int j)"
.br
.ti -1c
.RI "char * \fBget_next_line\fP (int fd)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* get_next_line (intfd)"

.PP
Definition at line 49 of file get_next_line\&.c\&.
.SS "char* my_read (intfd, char *str)"

.PP
Definition at line 17 of file get_next_line\&.c\&.
.SS "char* new_str (char *str, int *i, intj)"

.PP
Definition at line 37 of file get_next_line\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
