.TH "builtin/getvar.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
builtin/getvar.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <lib\&.h>\fP
.br
\fC#include 'builtin\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdelete_first_word\fP (char **wtab)"
.br
.ti -1c
.RI "int \fBmy_replace_key\fP (char **expr, \fBt_data\fP *data)"
.br
.ti -1c
.RI "char * \fBmy_cstrconcat\fP (char *s1, char *s2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void delete_first_word (char **wtab)"

.PP
Definition at line 15 of file getvar\&.c\&.
.SS "char* my_cstrconcat (char *s1, char *s2)"

.PP
Definition at line 50 of file getvar\&.c\&.
.SS "int my_replace_key (char **expr, \fBt_data\fP *data)"

.PP
Definition at line 28 of file getvar\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
