.TH "prompt_read_termcaps/insert_list_double.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prompt_read_termcaps/insert_list_double.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'shell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBt_history\fP * \fBinsert_list_double\fP (\fBt_history\fP *l, char *data)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBt_history\fP* insert_list_double (\fBt_history\fP *l, char *data)"

.PP
Definition at line 14 of file insert_list_double\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
