.TH "exe/is_builtin.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exe/is_builtin.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBis_builtin\fP (char *cmd)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int is_builtin (char *cmd)"

.PP
Definition at line 13 of file is_builtin\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
