.TH "is_exe.c" 3 "Fri May 22 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
is_exe.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBis_exe\fP (char *path)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int is_exe (char *path)"

.PP
Definition at line 15 of file is_exe\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
