.TH "prompt_read_termcaps/loop_read.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prompt_read_termcaps/loop_read.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'shell\&.h'\fP
.br
\fC#include 'lib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBclean\fP (char *c, const int nb)"
.br
.ti -1c
.RI "void * \fBchange_word\fP (\fBt_stock\fP *ptr)"
.br
.ti -1c
.RI "char * \fBloop\fP (\fBt_history\fP *list)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* change_word (\fBt_stock\fP *ptr)"

.PP
Definition at line 39 of file loop_read\&.c\&.
.SS "void clean (char *c, const intnb)"

.PP
Definition at line 16 of file loop_read\&.c\&.
.SS "char* loop (\fBt_history\fP *list)"

.PP
Definition at line 67 of file loop_read\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
