.TH "main.c" 3 "Fri May 22 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <signal\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'shell\&.h'\fP
.br
\fC#include 'ps1\&.h'\fP
.br
\fC#include 'lib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsignal_exit\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv, char **env)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv, char **env)"

.PP
Definition at line 24 of file main\&.c\&.
.SS "void signal_exit ()"

.PP
Definition at line 18 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
