.TH "make_env.c" 3 "Fri May 22 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
make_env.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'shell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreturn_index\fP (char **env, char *str)"
.br
.ti -1c
.RI "char ** \fBmake_env\fP (char **argp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char** make_env (char **argp)"

.PP
Definition at line 31 of file make_env\&.c\&.
.SS "int return_index (char **env, char *str)"

.PP
Definition at line 15 of file make_env\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
