.TH "lib/my/my_getnbr.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_getnbr.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcheck\fP (int nbr, int nbr_z)"
.br
.ti -1c
.RI "int \fBmy_getnbr_2\fP (char *str, int signe)"
.br
.ti -1c
.RI "int \fBmy_getnbr\fP (char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int check (intnbr, intnbr_z)"

.PP
Definition at line 11 of file my_getnbr\&.c\&.
.SS "int my_getnbr (char *str)"

.PP
Definition at line 48 of file my_getnbr\&.c\&.
.SS "int my_getnbr_2 (char *str, intsigne)"

.PP
Definition at line 19 of file my_getnbr\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
