.TH "lib/my/my_putchar.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_putchar.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmy_putchar\fP (char c, int fd)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void my_putchar (charc, intfd)"

.PP
Definition at line 13 of file my_putchar\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
