.TH "lib/my/my_put_nbr.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_put_nbr.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpower_10\fP (int nb)"
.br
.ti -1c
.RI "void \fBmy_put_nbr\fP (int nb)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void my_put_nbr (intnb)"

.PP
Definition at line 26 of file my_put_nbr\&.c\&.
.SS "int power_10 (intnb)"

.PP
Definition at line 13 of file my_put_nbr\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
