.TH "lib/my/my_putstr.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_putstr.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmy_putstr\fP (char *str, int fd)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void my_putstr (char *str, intfd)"

.PP
Definition at line 14 of file my_putstr\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
