.TH "lib/my/my_strdup.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_strdup.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'lib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBmy_strdup\fP (char *src)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* my_strdup (char *src)"

.PP
Definition at line 14 of file my_strdup\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
