.TH "lib/my/my_strncmp.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_strncmp.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_strncmp\fP (char *a, char *b, int n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_strncmp (char *a, char *b, intn)"

.PP
Definition at line 11 of file my_strncmp\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
