.TH "lib/my/my_strcat.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/my_strcat.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBmy_strcat\fP (char *dest, char *src)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* my_strcat (char *dest, char *src)"

.PP
Definition at line 11 of file my_strcat\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
