.TH "prompt_read_termcaps/print_cursor.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prompt_read_termcaps/print_cursor.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'shell\&.h'\fP
.br
\fC#include 'lib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_cursor_left\fP (const int nb)"
.br
.ti -1c
.RI "void \fBprint_cursor_right\fP (const int nb)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void print_cursor_left (const intnb)"

.PP
Definition at line 14 of file print_cursor\&.c\&.
.SS "void print_cursor_right (const intnb)"

.PP
Definition at line 31 of file print_cursor\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
