.TH "prompt.c" 3 "Fri May 22 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prompt.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'lib\&.h'\fP
.br
\fC#include 'shell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBclear_str\fP (char *str, int l)"
.br
.ti -1c
.RI "char * \fBepure_str\fP (char *str)"
.br
.ti -1c
.RI "char * \fBread_cmd\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* clear_str (char *str, intl)"

.PP
Definition at line 17 of file prompt\&.c\&.
.SS "char* epure_str (char *str)"

.PP
Definition at line 30 of file prompt\&.c\&.
.SS "char* read_cmd ()"

.PP
Definition at line 44 of file prompt\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
