.TH "prompt_read_termcaps/prompt_dyn.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prompt_read_termcaps/prompt_dyn.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <termios\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'shell\&.h'\fP
.br
\fC#include 'lib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBget_cmd\fP (\fBt_history\fP **list)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* get_cmd (\fBt_history\fP **list)"

.PP
Definition at line 45 of file prompt_dyn\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
