.TH "s_bref" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_bref \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <builtin\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBref\fP"
.br
.ti -1c
.RI "int(* \fBbuiltin\fP )(char **, \fBt_data\fP *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file builtin\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int(* builtin)(char **, \fBt_data\fP *)"

.PP
Definition at line 25 of file builtin\&.h\&.
.SS "char* ref"

.PP
Definition at line 24 of file builtin\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
