.TH "s_cmd" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_cmd \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shell\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char ** \fBtab\fP"
.br
.ti -1c
.RI "\fBt_list\fP * \fBredi_r\fP"
.br
.ti -1c
.RI "\fBt_list\fP * \fBredi_l\fP"
.br
.ti -1c
.RI "struct \fBs_cmd\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file shell\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBs_cmd\fP* next"

.PP
Definition at line 42 of file shell\&.h\&.
.SS "\fBt_list\fP* redi_l"

.PP
Definition at line 41 of file shell\&.h\&.
.SS "\fBt_list\fP* redi_r"

.PP
Definition at line 40 of file shell\&.h\&.
.SS "char** tab"

.PP
Definition at line 39 of file shell\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
