.TH "s_cmds" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_cmds \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shell\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_cmd\fP * \fBcmd\fP"
.br
.ti -1c
.RI "char \fBsep\fP"
.br
.ti -1c
.RI "struct \fBs_cmds\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file shell\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBt_cmd\fP* cmd"

.PP
Definition at line 47 of file shell\&.h\&.
.SS "struct \fBs_cmds\fP* next"

.PP
Definition at line 49 of file shell\&.h\&.
.SS "char sep"

.PP
Definition at line 48 of file shell\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
