.TH "s_data" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shell\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdynam_prompt\fP"
.br
.ti -1c
.RI "\fBt_alias\fP * \fBalias\fP"
.br
.ti -1c
.RI "\fBt_cmds\fP * \fBcmds\fP"
.br
.ti -1c
.RI "char ** \fBenv\fP"
.br
.ti -1c
.RI "char * \fBps1\fP"
.br
.ti -1c
.RI "int \fBreturn_exe\fP"
.br
.ti -1c
.RI "int \fBreturn_exit\fP"
.br
.ti -1c
.RI "\fBt_history\fP * \fBlist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 66 of file shell\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBt_alias\fP* alias"

.PP
Definition at line 69 of file shell\&.h\&.
.SS "\fBt_cmds\fP* cmds"

.PP
Definition at line 70 of file shell\&.h\&.
.SS "int dynam_prompt"

.PP
Definition at line 68 of file shell\&.h\&.
.SS "char** env"

.PP
Definition at line 71 of file shell\&.h\&.
.SS "\fBt_history\fP* list"

.PP
Definition at line 75 of file shell\&.h\&.
.SS "char* ps1"

.PP
Definition at line 72 of file shell\&.h\&.
.SS "int return_exe"

.PP
Definition at line 73 of file shell\&.h\&.
.SS "int return_exit"

.PP
Definition at line 74 of file shell\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
