.TH "s_format" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_format \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ps1\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBformat\fP"
.br
.ti -1c
.RI "void(* \fBptr_tab\fP )(char **env)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file ps1\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char format"

.PP
Definition at line 24 of file ps1\&.h\&.
.SS "void(* ptr_tab)(char **env)"

.PP
Definition at line 25 of file ps1\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
