.TH "s_stock" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_stock \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shell\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBcmd\fP"
.br
.ti -1c
.RI "char * \fBc\fP"
.br
.ti -1c
.RI "int \fBpos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file shell\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* c"

.PP
Definition at line 55 of file shell\&.h\&.
.SS "char* cmd"

.PP
Definition at line 54 of file shell\&.h\&.
.SS "int pos"

.PP
Definition at line 56 of file shell\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
