.TH "segfault.c" 3 "Fri May 22 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
segfault.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/wait\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsegfault\fP (int return_exe)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int segfault (intreturn_exe)"

.PP
Definition at line 15 of file segfault\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
