.TH "glob/stars.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glob/stars.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'shell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBis_stars\fP (char *path)"
.br
.ti -1c
.RI "int \fBif_stars\fP (char **res, char **str, int i, int k)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int if_stars (char **res, char **str, inti, intk)"

.PP
Definition at line 29 of file stars\&.c\&.
.SS "int is_stars (char *path)"

.PP
Definition at line 14 of file stars\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
