.TH "lib/my/str_to_word_tab.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/str_to_word_tab.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'lib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBis_sep\fP (char *seps, char c)"
.br
.ti -1c
.RI "int \fBhow_many_words\fP (char *str, char *seps)"
.br
.ti -1c
.RI "char ** \fBstr_to_word_tab\fP (char *str, char *seps)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int how_many_words (char *str, char *seps)"

.PP
Definition at line 26 of file str_to_word_tab\&.c\&.
.SS "int is_sep (char *seps, charc)"

.PP
Definition at line 15 of file str_to_word_tab\&.c\&.
.SS "char** str_to_word_tab (char *str, char *seps)"

.PP
Definition at line 46 of file str_to_word_tab\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
