.TH "builtin/top_builtin.c" 3 "Sun May 24 2015" "Version 3.0" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
builtin/top_builtin.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'builtin\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_redir_builtin\fP (\fBt_data\fP *data, \fBt_cmd\fP *cmd)"
.br
.ti -1c
.RI "int \fBbuiltin\fP (\fBt_data\fP *data, char **cmd)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int builtin (\fBt_data\fP *data, char **cmd)"

.PP
Definition at line 35 of file top_builtin\&.c\&.
.SS "int my_redir_builtin (\fBt_data\fP *data, \fBt_cmd\fP *cmd)"

.PP
Definition at line 16 of file top_builtin\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
